-- Do not edit this file --
-- Type Definitions to be used for input --
-- Created by Thijs Morlion --
-- 28/11/2011 14:18 --

Key_A = 0x41
Key_D = 0x44
Key_W = 0x57
Key_S = 0x53

Key_LEFT  = 0x25
Key_UP    = 0x26
Key_RIGHT = 0x27
Key_DOWN  = 0x28
Key_SPACE = 0x20
