#ifndef FALCONENGINE_FALCONLUABIND_H
#define FALCONENGINE_FALCONLUABIND_H
	#pragma warning(push)
		#pragma warning(disable:4251)
		#include "luabind/luabind.hpp"
		#include "luabind/adopt_policy.hpp"
		#include "luabind/class.hpp"
		#include "luabind/scope.hpp"
		#include "luabind/operator.hpp"
	#pragma warning(pop)
#endif //FALCONENGINE_FALCONLUABIND_H